### ISSUE TITLE
Directx games fullscreen mouse gone

### ISSUE THREAD

**Issue by vhanla** [danielng01/Iris-Builds#1]
I tried Iris, and my games while fullscreen doesn't show the mouse cursor. Any hint to restore it? I tried disabling and uninstalling Iris.

**Comment by danielng01** [comment]
Hi,
Uncheck use software cursor in System. I think this will help :)

-----Original Message-----

**Comment by vhanla** [comment]
That fixed it, thanks

**Comment by danielng01** [comment]
Great if you have other problems report them :)
