### ISSUE TITLE
Iris 0.9.2.5 ignores "use keyboard shortcut"

### ISSUE THREAD

**Issue by alexdevero** [danielng01/Iris-Builds#5]
Iris v0.9.2.5 on Windows ignores keyboard settings. I have the option for shortcuts ("use keyboard shortcut") disabled. Hover, Iris is still catching them and applying corresponding settings - pausing, magnification, etc. Issue is solved after reverting to version 0.9.2.4.

Iris version: 0.9.2.5
OS: Windows 10 (1703)

**Comment by danielng01** [comment]
Fixed download 0.9.2.5 again
